### PR TITLE
Determinism fixes

### PR DESCRIPTION
**Pull request by scele**
- Make wheel build deterministic by sorting files inside the zip
- Generate deterministic BUILD file for extracted wheels

### CODE REVIEW

**Comment by therc** [comment]
Does this explain the warnings I have been getting? In my case, I had 36 out of 53 wheels with mismatched digests. I'm wondering why the other 17 matched... is there a ~33% chance of that happening?

**Comment by therc** [comment]
Nevermind, the run I was inspecting was building only 36 of the wheels. So the other 17 weren't even being looked at.

**Comment by scele** [comment]
@therc I’d be interested if you can still repro mismatches with this. The only package I’ve seen mismatches with this change is `pycuda`, haven’t debugged yet why.

**Comment by therc** [comment]
I can't get any mismatches with my 190 packages now and I haven't tried with pycuda, either, but will have to tackle that soon. These Nvidia people and their misbehaving wheels. ;-)

**Comment by therc** [comment]
I don't get alerts, but I do see mismatching checksums between the bzl file and what's on disk. Just looking at packages starting with 'a':

```diff
$ diff -u built.txt inbzl.txt 
--- built.txt	2019-02-11 15:47:04.000000000 -0500
+++ inbzl.txt	2019-02-11 15:47:17.000000000 -0500
@@ -1,9 +1,9 @@
-ac30fd280b35af300979e4e39e8c0bcd5fa898d6439f03a170c9589532ee3e9d absl_py-0.7.0-py2-none-any.whl
+5aa0aea078316836bb81e13ee7991822a7bef07b29d38fcd81c905b919b6e3b2 absl_py-0.7.0-py2-none-any.whl
 16056c952e8029ce8db097edf0d7c2fe2ba9de15d30ba08aee2c5221273d8e23 amqp-2.4.1-py2.py3-none-any.whl
-6112b9addc4232dddcbb8630e64dbcfa873540fd8aac0dd786050ad7f6c39cec anyjson-0.3.3-py2-none-any.whl
+c45bda4bfaf4ca5d6878bd690a2f85aa2e3b0775b6482517dc1485bc91ffd803 anyjson-0.3.3-py2-none-any.whl
 2f1adbb7546ed199e3c90ef23ec95c5cf3585bac7d11fb7eb562a3fe89c64e87 asn1crypto-0.24.0-py2.py3-none-any.whl
 fb503b9e2fdd05609fbf557b916b4a7824171203701660f0c55bbf5a7a68713e astor-0.7.1-py2.py3-none-any.whl
 46cd033dddbc3dc602d64991949d43232cf08d53cd4c06cae224895d542d9358 astroid-1.4.5-py2.py3-none-any.whl
-fabfe0fb39f53034df1c62d6e6c9ff7711e1c8437858830828bc406e5200657a autoflake-1.0-py2-none-any.whl
-1c1d0e582d16c725778bcbb868380e946992ac3dfd46c99fcebe0af8a93427f1 aws_requests_auth-0.3.3-py2-none-any.whl
+697f0e4099c94b1ce6098a02f13ece1c17267bae62a57b720ecbd86a295dff64 autoflake-1.0-py2-none-any.whl
+19455ce901cc6d05e6bebc6192e864e39894f9894d59ccd35fb151c7e40d4384 aws_requests_auth-0.3.3-py2-none-any.whl
 61891f987c70b4415fcccf6198d272d0f1c278cd53aaa23f4d3f2ba6475d8ccd awscli-1.16.96-py2.py3-none-any.whl
```

`built.txt` is the output from running shasum against a fresh `pip/build-directory`. `inbzl.txt` is what's in the `.bzl` file. The ones that match are the prebuilt wheels. I noticed that new wheels have today's timestamps for metadata files:

```
     2268  02-11-2019 20:24   absl_py-0.7.0.dist-info/METADATA
       92  02-11-2019 20:24   absl_py-0.7.0.dist-info/WHEEL
        5  02-11-2019 20:24   absl_py-0.7.0.dist-info/top_level.txt
     2482  02-11-2019 20:24   absl_py-0.7.0.dist-info/RECORD
```
Actually, that time is in the future, so it's maybe showing UTC...
Anyway, the sha256 value in the bzl files hasn't changed in a while, even with multiple rebuild attempts (all with different dist-info timestamps, which should have resulted in different checksums), so I'm wondering what's going on...

**Comment by therc** [comment]
I think I know what's going on or at least contributing to it.
There is code (strip_wheel) to remove the timestamps. So I assume that the sha256 checksum in the bazel files is for the stripped wheels. The check is done against the stripped version, which is never persisted to disk, so it succeeds.

That works, but it's very confusing, especially if you want to automate things. (I still can't get the built wheels cached, so I was trying to script it myself.)
Should wheels be output with stripped timestamps in the first place?

**Pull request merged**
